name: Erlang CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    container:
      image: erlang:23.1.5

    steps:
    - uses: actions/checkout@v2
    - name: Compile
      run: make
    - name: Run tests
      run: make eunit
